[package]
name = "kurtbuilds_fixture_derive"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "A library for deriving implementations for the fixture crate"

[lib]
proc-macro = true
name = "fixture_derive"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0.72"
